name: ecommerce_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # State management
  flutter_bloc: ^8.1.3

  # Comparing dart objects
  equatable: ^2.0.5

  # Service locator
  get_it: ^7.6.4

  # Date format
  intl: ^0.18.1

  # String format
  sprintf: ^7.0.0

  # Hooks
  flutter_hooks: ^0.20.3

  # Cached image
  cached_network_image: ^3.3.1

  # Dio
  dio: ^5.3.3

  # SVG
  flutter_svg: ^2.0.9

  # Bloc
  bloc: ^8.1.2

  # Bot toast
  bot_toast: ^4.1.3

  # Assets generate
  flutter_gen: ^5.4.0

  # Screen util
  flutter_screenutil: ^5.9.0

  # Easy location
  easy_localization: ^3.0.3

  # SharedPreferences
  shared_preferences: ^2.2.2

  # Pull to refresh, load more
  pull_to_refresh: ^2.0.0

  # Slider
  carousel_slider: ^4.2.1

  # Smart grid view
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.4.0

flutter_gen:
  integrations:
    flutter_svg: true

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/Muli.ttf
        - asset: assets/fonts/Muli-Italic.ttf
          style: italic
        - asset: assets/fonts/Muli-Bold.ttf
          weight: 700
